import {
  ArrowRight,
  ArrowRightLeft,
  AudioWaveform,
  BarChart3,
  BrainCircuit,
  BriefcaseBusiness,
  CalendarDays,
  Check,
  ChevronDown,
  Clock3,
  Coins,
  Command,
  Copy,
  Crosshair,
  Database,
  Download,
  FileText,
  Folder,
  FolderKanban,
  LayoutGrid,
  Link2,
  ListFilter,
  Mail,
  Maximize2,
  Mic,
  Minus,
  MoreHorizontal,
  Paperclip,
  Pause,
  Pencil,
  Plus,
  ReceiptText,
  Search,
  Send,
  ShieldCheck,
  Sparkles,
  ThumbsUp,
  TrendingUp,
  UsersRound,
  Volume2,
  X,
  type LucideIcon,
} from "lucide-react";
import type { IconName } from "@/lib/ops-demo-data";

type IconProps = {
  name: IconName;
  size?: number;
  strokeWidth?: number;
  className?: string;
};

const icons: Record<IconName, LucideIcon> = {
  grid: LayoutGrid,
  spark: Sparkles,
  cycle: ArrowRightLeft,
  mail: Mail,
  document: FileText,
  users: UsersRound,
  calendar: CalendarDays,
  database: Database,
  chart: BarChart3,
  brain: BrainCircuit,
  search: Search,
  plus: Plus,
  minus: Minus,
  fit: Maximize2,
  chevron: ChevronDown,
  arrow: ArrowRight,
  microphone: Mic,
  attach: Paperclip,
  command: Command,
  check: Check,
  clock: Clock3,
  filter: ListFilter,
  dots: MoreHorizontal,
  close: X,
  send: Send,
  briefcase: BriefcaseBusiness,
  coins: Coins,
  trend: TrendingUp,
  target: Crosshair,
  link: Link2,
  shield: ShieldCheck,
  invoice: ReceiptText,
  project: FolderKanban,
  copy: Copy,
  thumb: ThumbsUp,
  edit: Pencil,
  download: Download,
  volume: Volume2,
  pause: Pause,
  waveform: AudioWaveform,
  folder: Folder,
};

export function OpsIcon({ name, size = 20, strokeWidth = 1.65, className }: IconProps) {
  const Icon = icons[name];
  return <Icon aria-hidden="true" className={className} size={size} strokeWidth={strokeWidth} />;
}
