export type PageId =
  | "overview"
  | "missions"
  | "leads"
  | "crm"
  | "campaigns"
  | "inbox"
  | "linkedin";

export type MissionStatus = "En cours" | "Approbation" | "Terminée" | "Suspendue";

export const missions = [
  {
    id: "MIS-028",
    title: "Trouver 80 industriels en Bretagne",
    objective: "Détecter les sociétés de 20 à 200 salariés avec un signal de maintenance récent.",
    status: "En cours" as MissionStatus,
    progress: 68,
    currentStep: "Enrichissement des 50 meilleurs comptes",
    source: "Serper · data.gouv · Apollo",
    leads: 91,
    budget: "72,40 € / 150 €",
    owner: "Agent IA",
    created: "Aujourd’hui, 08:42",
  },
  {
    id: "MIS-027",
    title: "Réactiver les devis perdus — timing",
    objective: "Recontacter les opportunités supérieures à 15 k€ perdues depuis 6 à 18 mois.",
    status: "Approbation" as MissionStatus,
    progress: 84,
    currentStep: "Validation de 12 messages avant envoi",
    source: "CRM · Signaux marché",
    leads: 25,
    budget: "18,20 € / 50 €",
    owner: "Vous",
    created: "Hier, 17:10",
  },
  {
    id: "MIS-026",
    title: "Identifier les prescripteurs Grand Ouest",
    objective: "Cartographier les bureaux d’études et experts-comptables pouvant recommander l’offre.",
    status: "En cours" as MissionStatus,
    progress: 31,
    currentStep: "Qualification des relations existantes",
    source: "CRM · Maps · LinkedIn",
    leads: 42,
    budget: "9,60 € / 80 €",
    owner: "Agent IA",
    created: "12 juil., 14:25",
  },
  {
    id: "MIS-025",
    title: "Préparer le salon SEPEM Angers",
    objective: "Prioriser les exposants et préparer les demandes de rendez-vous avant le salon.",
    status: "Terminée" as MissionStatus,
    progress: 100,
    currentStep: "Rapport livré",
    source: "Site salon · CRM · Apollo",
    leads: 63,
    budget: "44,10 € / 100 €",
    owner: "Agent IA",
    created: "08 juil., 10:03",
  },
];

export const leads = [
  {
    id: "LD-1048",
    company: "Armor Process",
    city: "Lorient",
    naf: "33.12Z",
    size: "48 salariés",
    revenue: "8,4 M€",
    contact: "Claire Le Goff",
    role: "Directrice opérations",
    email: "claire@armor-process.fr",
    score: 94,
    signal: "Recrute un responsable maintenance",
    age: "Il y a 2 j",
    sources: ["Maps", "data.gouv", "Apollo"],
    state: "Prêt",
  },
  {
    id: "LD-1047",
    company: "Bretagne Thermique",
    city: "Quimper",
    naf: "28.25Z",
    size: "86 salariés",
    revenue: "14,1 M€",
    contact: "Thomas Kerneis",
    role: "Directeur général",
    email: "thomas@bretagne-thermique.fr",
    score: 91,
    signal: "Nouvelle ligne de production annoncée",
    age: "Il y a 5 j",
    sources: ["Maps", "Presse", "Apollo"],
    state: "Prêt",
  },
  {
    id: "LD-1046",
    company: "Soframec Industrie",
    city: "Vannes",
    naf: "25.62B",
    size: "31 salariés",
    revenue: "5,7 M€",
    contact: "Élodie Martin",
    role: "Responsable achats",
    email: "elodie@soframec.fr",
    score: 87,
    signal: "Déménagement vers un site de 4 000 m²",
    age: "Il y a 8 j",
    sources: ["data.gouv", "Apollo"],
    state: "À vérifier",
  },
  {
    id: "LD-1045",
    company: "Kerfluid Systems",
    city: "Brest",
    naf: "28.29B",
    size: "112 salariés",
    revenue: "22,6 M€",
    contact: "Marc Philippe",
    role: "Responsable maintenance",
    email: "marc@kerfluid.fr",
    score: 85,
    signal: "Levée de fonds de 3,2 M€",
    age: "Il y a 11 j",
    sources: ["Presse", "Apollo"],
    state: "Prêt",
  },
  {
    id: "LD-1044",
    company: "Ateliers du Trégor",
    city: "Lannion",
    naf: "25.11Z",
    size: "27 salariés",
    revenue: "4,2 M€",
    contact: "Sophie Rault",
    role: "Co-gérante",
    email: "sophie@ateliers-tregor.fr",
    score: 81,
    signal: "Avis client mentionnant un pic d’activité",
    age: "Il y a 13 j",
    sources: ["Maps", "data.gouv"],
    state: "Contact manquant",
  },
  {
    id: "LD-1043",
    company: "Ouest Convoyage",
    city: "Rennes",
    naf: "49.41B",
    size: "64 salariés",
    revenue: "11,9 M€",
    contact: "Nicolas Piriou",
    role: "Directeur technique",
    email: "nicolas@ouest-convoyage.fr",
    score: 78,
    signal: "Appel d’offres public détecté",
    age: "Il y a 15 j",
    sources: ["data.gouv", "Apollo"],
    state: "À vérifier",
  },
];

export const crmOpportunities = [
  {
    company: "MecaOuest",
    contact: "Julien Morvan",
    amount: "46 000 €",
    lost: "14 févr. 2025",
    reason: "Timing",
    signal: "Nouveau directeur industriel",
    score: 92,
  },
  {
    company: "Groupe Althéa",
    contact: "Sarah Vimont",
    amount: "31 500 €",
    lost: "03 juin 2025",
    reason: "Projet reporté",
    signal: "Budget 2026 voté",
    score: 88,
  },
  {
    company: "Noroît Équipements",
    contact: "Hugo Perrin",
    amount: "24 800 €",
    lost: "19 sept. 2025",
    reason: "Timing",
    signal: "Deux recrutements ouverts",
    score: 84,
  },
  {
    company: "Ligeris Froid",
    contact: "Anaïs Tellier",
    amount: "18 200 €",
    lost: "07 nov. 2025",
    reason: "Priorité interne",
    signal: "Aucun signal fort",
    score: 69,
  },
];

export const inboxThreads = [
  {
    id: 1,
    name: "Claire Le Goff",
    company: "Armor Process",
    initials: "CL",
    channel: "Email",
    category: "Positive",
    preview: "Oui, le sujet est d’actualité. Êtes-vous disponible jeudi matin ?",
    time: "10:24",
    unread: true,
  },
  {
    id: 2,
    name: "Thomas Kerneis",
    company: "Bretagne Thermique",
    initials: "TK",
    channel: "LinkedIn",
    category: "Question",
    preview: "Pouvez-vous préciser comment vous vous connectez à notre ERP ?",
    time: "09:52",
    unread: true,
  },
  {
    id: 3,
    name: "Sophie Rault",
    company: "Ateliers du Trégor",
    initials: "SR",
    channel: "Formulaire",
    category: "Positive",
    preview: "Nous cherchons justement à fiabiliser le suivi commercial.",
    time: "Hier",
    unread: false,
  },
  {
    id: 4,
    name: "Marc Philippe",
    company: "Kerfluid Systems",
    initials: "MP",
    channel: "Email",
    category: "Plus tard",
    preview: "Revenez vers moi après notre arrêt technique de septembre.",
    time: "Hier",
    unread: false,
  },
  {
    id: 5,
    name: "Olivier Brun",
    company: "Techniflux",
    initials: "OB",
    channel: "Appel manqué",
    category: "À qualifier",
    preview: "Appel entrant manqué · 01:34",
    time: "Lun.",
    unread: false,
  },
];

export const campaigns = [
  {
    name: "Industrie Bretagne · signal maintenance",
    status: "Active",
    audience: 91,
    sent: 54,
    replies: 8,
    positive: 4,
    meetings: 2,
    owner: "Agent IA",
    progress: 59,
    next: "18 envois demain à 08:45",
  },
  {
    name: "Réactivation · devis perdus timing",
    status: "À approuver",
    audience: 25,
    sent: 0,
    replies: 0,
    positive: 0,
    meetings: 0,
    owner: "Vous",
    progress: 0,
    next: "12 messages à valider",
  },
  {
    name: "Prescripteurs · Grand Ouest",
    status: "Brouillon",
    audience: 42,
    sent: 0,
    replies: 0,
    positive: 0,
    meetings: 0,
    owner: "Agent IA",
    progress: 0,
    next: "En attente de l’audience finale",
  },
];

export const linkedInPosts = [
  {
    status: "À valider",
    date: "Demain · 08:10",
    hook: "Le vrai coût d’une machine arrêtée n’apparaît jamais sur le devis de maintenance.",
    theme: "Retour terrain",
  },
  {
    status: "Planifié",
    date: "Mer. 16 juil. · 12:15",
    hook: "3 signaux qui annoncent une panne avant même que les capteurs ne la voient.",
    theme: "Expertise",
  },
  {
    status: "Brouillon",
    date: "Ven. 18 juil. · 08:30",
    hook: "Ce que notre équipe a appris après 120 audits de sites industriels.",
    theme: "Preuve",
  },
];

export const weeklyActivity = [12, 19, 16, 27, 25, 42, 38, 53, 47, 61, 58, 74];
